In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [18]:
iowa = pd.read_csv("iowa.csv", dtype = {'Zip Code' : 'object', 'Item Number' : 'object', 'Category' : 'object', 'Vendor Number' : 'object'})
iowa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26592863 entries, 0 to 26592862
Data columns (total 24 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Invoice/Item Number    object
 1   Date                   object
 2   Store Number           int64
 3   Store Name             object
 4   Address                object
 5   City                   object
 6   Zip Code               object
 7   Store Location         object
 8   County Number          float64
 9   County                 object
 10  Category               object
 11  Category Name          object
 12  Vendor Number          object
 13  Vendor Name            object
 14  Item Number            object
 15  Item Description       object
 16  Pack                   int64
 17  Bottle Volume (ml)     int64
 18  State Bottle Cost      float64
 19  State Bottle Retail    float64
 20  Bottles Sold           int64
 21  Sale (Dollars)         float64
 22  Volume Sold (Liters)   float64
 23  Volume Sold (Gallons)  float64
dtypes: float64(6), int64(4), object(14)
memory usage: 4.8+ GB

In [4]:
iowa.head()

,Invoice/Item Number,Date,Store Number,Store Name,Address,City,Zip Code,Store Location,County Number,County,...,Item Number,Item Description,Pack,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons)
0,INV-11440700004,04/11/2018,5514,JOHNCY'S LIQUOR STORE,585 HWY 965 STE D & E,NORTH LIBERTY,52317,POINT (-91.60761 41.738129),52.0,JOHNSON,...,36908,MCCORMICK VODKA PET,6,1750,7.47,11.21,6,67.26,10.5,2.77
1,INV-11583000132,04/18/2018,2623,HY-VEE FOOD STORE #4 / SIOUX CITY,2827 HAMILTON BLVD,SIOUX CITY,51104,POINT (-96.417783 42.519886),97.0,WOODBURY,...,5006,GLENFIDDICH 12YR SPECIAL RESERVE,12,750,23.48,35.22,2,68.94,1.5,0.40
2,INV-11516100032,04/16/2018,4967,JEFF'S MARKET / BLUE GRASS,"102, W MAYNE ST",BLUE GRASS,52726,POINT (-90.766126 41.509119),82.0,SCOTT,...,41693,UV BLUE (RASPBERRY) VODKA,12,750,6.50,9.75,2,19.50,1.5,0.40
3,INV-11469500012,04/12/2018,5146,FAREWAY STORES #153 / W DES MOINES,329 GRAND AVE,WEST DES MOINES,50265,POINT (-93.70689 41.58269000000001),77.0,POLK,...,37348,PHILLIPS VODKA,6,1750,7.60,11.40,6,68.40,10.5,2.77
4,INV-11457200003,04/12/2018,2515,HY-VEE FOOD STORE #1 / MASON CITY,2400 4TH ST SW,MASON CITY,50401,POINT (-93.23551 43.149557),17.0,CERRO GORDO,...,11777,BLACK VELVET,12,1000,6.63,9.95,12,119.40,12.0,3.17

In [9]:
iowa['County Number'] = pd.to_numeric(iowa['County Number'], errors = 'coerce')

,Invoice/Item Number,Date,Store Number,Store Name,Address,City,Zip Code,Store Location,County Number,County,...,Item Number,Item Description,Pack,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons)
0,INV-11440700004,04/11/2018,5514,JOHNCY'S LIQUOR STORE,585 HWY 965 STE D & E,NORTH LIBERTY,52317,POINT (-91.60761 41.738129),52.0,JOHNSON,...,36908,MCCORMICK VODKA PET,6,1750,7.47,11.21,6,67.26,10.50,2.77
1,INV-11583000132,04/18/2018,2623,HY-VEE FOOD STORE #4 / SIOUX CITY,2827 HAMILTON BLVD,SIOUX CITY,51104,POINT (-96.417783 42.519886),97.0,WOODBURY,...,5006,GLENFIDDICH 12YR SPECIAL RESERVE,12,750,23.48,35.22,2,68.94,1.50,0.40
2,INV-11516100032,04/16/2018,4967,JEFF'S MARKET / BLUE GRASS,"102, W MAYNE ST",BLUE GRASS,52726,POINT (-90.766126 41.509119),82.0,SCOTT,...,41693,UV BLUE (RASPBERRY) VODKA,12,750,6.50,9.75,2,19.50,1.50,0.40
3,INV-11469500012,04/12/2018,5146,FAREWAY STORES #153 / W DES MOINES,329 GRAND AVE,WEST DES MOINES,50265,POINT (-93.70689 41.58269000000001),77.0,POLK,...,37348,PHILLIPS VODKA,6,1750,7.60,11.40,6,68.40,10.50,2.77
4,INV-11457200003,04/12/2018,2515,HY-VEE FOOD STORE #1 / MASON CITY,2400 4TH ST SW,MASON CITY,50401,POINT (-93.23551 43.149557),17.0,CERRO GORDO,...,11777,BLACK VELVET,12,1000,6.63,9.95,12,119.40,12.00,3.17
5,INV-11630600023,04/23/2018,5244,THE OX & WREN SPIRITS AND GIFTS,708 2ND AVE SE,CRESCO,52136,POINT (-92.106529 43.371131),45.0,HOWARD,...,64868,FIREBALL CINNAMON WHISKEY,6,1750,15.33,23.00,6,138.00,10.50,2.77
6,INV-11417500008,04/10/2018,3769,WAL-MART 0753 / CEDAR FALL,525 BRANDILYNN BLVD,CEDAR FALLS,50613,POINT (-92.440394 42.485042),7.0,BLACK HAWK,...,22156,WILD TURKEY 101,12,750,14.00,21.00,12,243.00,9.00,2.38
7,INV-11606400047,04/19/2018,2648,HY-VEE #4 / WDM,555 S 51ST ST,WEST DES MOINES,50265,POINT (-93.773557 41.561197),77.0,POLK,...,89846,TRES GENERACIONES ANEJO,6,750,20.99,31.49,2,62.98,1.50,0.40
8,INV-11634800078,04/23/2018,5236,"GIGGLE JUICE LIQUOR STATION, LLC",600 W MAIN ST,ANAMOSA,52205,POINT (-91.29083400000002 42.108203),53.0,JONES,...,36604,DEEP EDDY ORANGE MINI,6,600,4.92,7.38,1,7.38,0.60,0.16
9,INV-11560500001,04/18/2018,3647,WAL-MART 2889 / CLINTON,2715 SOUTH 25TH ST,CLINTON,52732,POINT (-90.245005 41.818874),23.0,CLINTON,...,34821,SVEDKA VODKA,6,1750,13.00,19.50,12,234.00,21.00,5.55
10,INV-11573200019,04/18/2018,5515,FINE LIQUOR & TOBACCO,821 ALBIA RD STE B,OTTUMWA,52501,POINT (-92.433211 41.008378),90.0,WAPELLO,...,28210,BOMBAY SAPPHIRE EAST,12,750,13.50,20.25,3,60.75,2.25,0.59
11,INV-11629700055,04/23/2018,2651,HY-VEE / WAVERLY,1311 4 STREET SW,WAVERLY,50677,POINT (-92.475403 42.712263),9.0,BREMER,...,45247,PARAMOUNT GOLD RUM,12,1000,4.42,6.63,1,6.63,1.00,0.26
12,INV-11484500042,04/13/2018,5327,MEGA SAVER,3540 W BROADWAY,COUNCIL BLUFFS,51501,POINT (-95.903763 41.261907),78.0,POTTAWATTAMIE,...,52593,E & J VS BRANDY,24,200,2.00,3.00,3,9.00,0.60,0.16
13,INV-11563100218,04/18/2018,2565,HY-VEE FOOD STORE / SPENCER,819 N GRAND AVE,SPENCER,51301,POINT (-95.14506 43.145897),21.0,CLAY,...,77698,SMIRNOFF ORANGE,12,750,8.25,12.38,2,24.76,1.50,0.40
14,INV-11438900032,04/11/2018,5515,FINE LIQUOR & TOBACCO,821 ALBIA RD STE B,OTTUMWA,52501,POINT (-92.433211 41.008378),90.0,WAPELLO,...,52596,E & J VS,12,750,6.00,9.00,6,54.00,4.50,1.19

In [12]:
iowa['County Number'].value_counts(dropna = False)

77.0    4459618
NaN     2460020
57.0    2013416
82.0    1472224
7.0     1353303
         ...
2.0       19865
93.0      18725
26.0      17960
80.0      16297
36.0       4310
Name: County Number, Length: 100, dtype: int64

In [13]:
iowa[iowa['County Number'].isna()]

,Invoice/Item Number,Date,Store Number,Store Name,Address,City,Zip Code,Store Location,County Number,County,...,Item Number,Item Description,Pack,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons)
16796,INV-11832200022,05/01/2018,4777,CASEY'S GENERAL STORE #1365 / PAULLINA,NaN,NaN,NaN,NaN,NaN,NaN,...,37886,SEAGRAMS VODKA,12,750,5.38,8.07,6,48.42,4.50,1.19
78409,INV-11832200021,05/01/2018,4777,CASEY'S GENERAL STORE #1365 / PAULLINA,NaN,NaN,NaN,NaN,NaN,NaN,...,36904,MCCORMICK VODKA PET,24,375,1.80,2.70,12,32.40,4.50,1.19
84910,INV-11832200012,05/01/2018,4777,CASEY'S GENERAL STORE #1365 / PAULLINA,NaN,NaN,NaN,NaN,NaN,NaN,...,26821,JACK DANIELS OLD #7 BLACK LBL MINI,12,500,9.06,13.59,2,27.18,1.00,0.26
85270,INV-11832200003,05/01/2018,4777,CASEY'S GENERAL STORE #1365 / PAULLINA,NaN,NaN,NaN,NaN,NaN,NaN,...,11297,CROWN ROYAL CANADIAN WHISKY,12,1000,18.89,28.34,6,170.04,6.00,1.59
87391,INV-11832200001,05/01/2018,4777,CASEY'S GENERAL STORE #1365 / PAULLINA,NaN,NaN,NaN,NaN,NaN,NaN,...,1799,CAPTAIN MORGAN SPICED BARREL,6,1750,18.00,27.00,6,162.00,10.50,2.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26539746,INV-11288900008,04/03/2018,4777,CASEY'S GENERAL STORE #1365 / PAULLINA,NaN,NaN,NaN,NaN,NaN,NaN,...,26820,JACK DANIELS OLD #7 BLACK LBL FLAT,24,375,7.50,11.25,6,67.50,2.25,0.59
26539959,INV-11288900017,04/03/2018,4777,CASEY'S GENERAL STORE #1365 / PAULLINA,NaN,NaN,NaN,NaN,NaN,NaN,...,64858,FIREBALL CINNAMON WHISKEY MINI DISPENSER,1,3000,30.00,45.00,4,180.00,12.00,3.17
26542633,INV-11288900015,04/03/2018,4777,CASEY'S GENERAL STORE #1365 / PAULLINA,NaN,NaN,NaN,NaN,NaN,NaN,...,41989,UV CAKE VODKA,12,750,6.50,9.75,3,29.25,2.25,0.59
26553855,INV-11288900007,04/03/2018,4777,CASEY'S GENERAL STORE #1365 / PAULLINA,NaN,NaN,NaN,NaN,NaN,NaN,...,19066,JIM BEAM,12,750,10.49,15.74,6,94.44,4.50,1.19
26563008,INV-11288900005,04/03/2018,4777,CASEY'S GENERAL STORE #1365 / PAULLINA,NaN,NaN,NaN,NaN,NaN,NaN,...,11788,BLACK VELVET,6,1750,10.45,15.68,12,188.16,21.00,5.55

In [14]:
iowa

,Invoice/Item Number,Date,Store Number,Store Name,Address,City,Zip Code,Store Location,County Number,County,...,Item Number,Item Description,Pack,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons)
0,INV-11440700004,04/11/2018,5514,JOHNCY'S LIQUOR STORE,585 HWY 965 STE D & E,NORTH LIBERTY,52317,POINT (-91.60761 41.738129),52.0,JOHNSON,...,36908,MCCORMICK VODKA PET,6,1750,7.47,11.21,6,67.26,10.50,2.77
1,INV-11583000132,04/18/2018,2623,HY-VEE FOOD STORE #4 / SIOUX CITY,2827 HAMILTON BLVD,SIOUX CITY,51104,POINT (-96.417783 42.519886),97.0,WOODBURY,...,5006,GLENFIDDICH 12YR SPECIAL RESERVE,12,750,23.48,35.22,2,68.94,1.50,0.40
2,INV-11516100032,04/16/2018,4967,JEFF'S MARKET / BLUE GRASS,"102, W MAYNE ST",BLUE GRASS,52726,POINT (-90.766126 41.509119),82.0,SCOTT,...,41693,UV BLUE (RASPBERRY) VODKA,12,750,6.50,9.75,2,19.50,1.50,0.40
3,INV-11469500012,04/12/2018,5146,FAREWAY STORES #153 / W DES MOINES,329 GRAND AVE,WEST DES MOINES,50265,POINT (-93.70689 41.58269000000001),77.0,POLK,...,37348,PHILLIPS VODKA,6,1750,7.60,11.40,6,68.40,10.50,2.77
4,INV-11457200003,04/12/2018,2515,HY-VEE FOOD STORE #1 / MASON CITY,2400 4TH ST SW,MASON CITY,50401,POINT (-93.23551 43.149557),17.0,CERRO GORDO,...,11777,BLACK VELVET,12,1000,6.63,9.95,12,119.40,12.00,3.17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26592858,INV-11623600016,04/20/2018,5494,WHITE OAK STATION #53,2024 5TH AVE,COUNCIL BLUFFS,51501,POINT (-95.874965 41.25712),78.0,POTTAWATTAMIE,...,19064,JIM BEAM,24,375,5.50,8.25,5,41.25,1.88,0.50
26592859,INV-11527700017,04/17/2018,4485,DYNO'S 51 / SANBORN,101 W 7TH ST,SANBORN,51248,POINT (-95.656064 43.186035000000004),71.0,O'BRIEN,...,84207,99 ROOTBEER MINI,10,600,6.00,9.00,2,18.00,1.20,0.32
26592860,INV-11481100023,04/13/2018,4602,CHEAP SMOKES / BEER CITY,58231 190TH ST,PACIFIC JUNCTION,51561,POINT (-95.822983 41.041739),65.0,MILLS,...,43302,CAPTAIN MORGAN BLACK SPICED,12,750,10.00,15.00,1,15.00,0.75,0.20
26592861,INV-11434500122,04/11/2018,4509,AJ'S LIQUOR II,2515 CHAMBERLAIN,AMES,50010,POINT (-93.650838 42.021461),85.0,STORY,...,77880,SMIRNOFF SOURS WATERMELON,12,750,8.25,12.38,12,148.56,9.00,2.38
26592862,INV-11539400080,04/17/2018,2545,HY-VEE DRUGSTORE / IOWA CITY,310 N 1ST ST,IOWA CITY,52245,POINT (-91.528105 42.207428),52.0,JOHNSON,...,45886,SAILOR JERRY SPICED NAVY RUM,12,750,9.65,14.48,3,43.44,2.25,0.59

In [20]:
iowa1 = iowa.drop(['Address', 'County Number', 'Volume Sold (Gallons)'], axis = 1)
iowa1.head()

,Invoice/Item Number,Date,Store Number,Store Name,City,Zip Code,Store Location,County,Category,Category Name,...,Vendor Name,Item Number,Item Description,Pack,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters)
0,INV-11440700004,04/11/2018,5514,JOHNCY'S LIQUOR STORE,NORTH LIBERTY,52317,POINT (-91.60761 41.738129),JOHNSON,1031100,AMERICAN VODKAS,...,MCCORMICK DISTILLING CO.,36908,MCCORMICK VODKA PET,6,1750,7.47,11.21,6,67.26,10.5
1,INV-11583000132,04/18/2018,2623,HY-VEE FOOD STORE #4 / SIOUX CITY,SIOUX CITY,51104,POINT (-96.417783 42.519886),WOODBURY,1012300,SINGLE MALT SCOTCH,...,WILLIAM GRANT & SONS INC,5006,GLENFIDDICH 12YR SPECIAL RESERVE,12,750,23.48,35.22,2,68.94,1.5
2,INV-11516100032,04/16/2018,4967,JEFF'S MARKET / BLUE GRASS,BLUE GRASS,52726,POINT (-90.766126 41.509119),SCOTT,1031200,AMERICAN FLAVORED VODKA,...,PHILLIPS BEVERAGE,41693,UV BLUE (RASPBERRY) VODKA,12,750,6.50,9.75,2,19.50,1.5
3,INV-11469500012,04/12/2018,5146,FAREWAY STORES #153 / W DES MOINES,WEST DES MOINES,50265,POINT (-93.70689 41.58269000000001),POLK,1031100,AMERICAN VODKAS,...,PHILLIPS BEVERAGE,37348,PHILLIPS VODKA,6,1750,7.60,11.40,6,68.40,10.5
4,INV-11457200003,04/12/2018,2515,HY-VEE FOOD STORE #1 / MASON CITY,MASON CITY,50401,POINT (-93.23551 43.149557),CERRO GORDO,1012100,CANADIAN WHISKIES,...,CONSTELLATION BRANDS INC,11777,BLACK VELVET,12,1000,6.63,9.95,12,119.40,12.0

In [16]:
iowa1[['Vendor Name', 'Vendor Number']]

                       Vendor Name  Vendor Number
0         MCCORMICK DISTILLING CO.          300.0
1         WILLIAM GRANT & SONS INC          240.0
2                PHILLIPS BEVERAGE          380.0
3                PHILLIPS BEVERAGE          380.0
4         CONSTELLATION BRANDS INC          115.0
...                            ...            ...
26592858           JIM BEAM BRANDS           65.0
26592859     SAZERAC NORTH AMERICA           55.0
26592860           DIAGEO AMERICAS          260.0
26592861           DIAGEO AMERICAS          260.0
26592862  WILLIAM GRANT & SONS INC          240.0

[26592863 rows x 2 columns]

In [21]:
iowa2 = iowa1.drop(['Pack', 'Bottle Volume (ml)'], axis = 1)
iowa2.head()

,Invoice/Item Number,Date,Store Number,Store Name,City,Zip Code,Store Location,County,Category,Category Name,Vendor Number,Vendor Name,Item Number,Item Description,State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters)
0,INV-11440700004,04/11/2018,5514,JOHNCY'S LIQUOR STORE,NORTH LIBERTY,52317,POINT (-91.60761 41.738129),JOHNSON,1031100,AMERICAN VODKAS,300,MCCORMICK DISTILLING CO.,36908,MCCORMICK VODKA PET,7.47,11.21,6,67.26,10.5
1,INV-11583000132,04/18/2018,2623,HY-VEE FOOD STORE #4 / SIOUX CITY,SIOUX CITY,51104,POINT (-96.417783 42.519886),WOODBURY,1012300,SINGLE MALT SCOTCH,240,WILLIAM GRANT & SONS INC,5006,GLENFIDDICH 12YR SPECIAL RESERVE,23.48,35.22,2,68.94,1.5
2,INV-11516100032,04/16/2018,4967,JEFF'S MARKET / BLUE GRASS,BLUE GRASS,52726,POINT (-90.766126 41.509119),SCOTT,1031200,AMERICAN FLAVORED VODKA,380,PHILLIPS BEVERAGE,41693,UV BLUE (RASPBERRY) VODKA,6.50,9.75,2,19.50,1.5
3,INV-11469500012,04/12/2018,5146,FAREWAY STORES #153 / W DES MOINES,WEST DES MOINES,50265,POINT (-93.70689 41.58269000000001),POLK,1031100,AMERICAN VODKAS,380,PHILLIPS BEVERAGE,37348,PHILLIPS VODKA,7.60,11.40,6,68.40,10.5
4,INV-11457200003,04/12/2018,2515,HY-VEE FOOD STORE #1 / MASON CITY,MASON CITY,50401,POINT (-93.23551 43.149557),CERRO GORDO,1012100,CANADIAN WHISKIES,115,CONSTELLATION BRANDS INC,11777,BLACK VELVET,6.63,9.95,12,119.40,12.0

In [22]:
iowa2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26592863 entries, 0 to 26592862
Data columns (total 19 columns):
 #   Column                Dtype
---  ------                -----
 0   Invoice/Item Number   object
 1   Date                  object
 2   Store Number          int64
 3   Store Name            object
 4   City                  object
 5   Zip Code              object
 6   Store Location        object
 7   County                object
 8   Category              object
 9   Category Name         object
 10  Vendor Number         object
 11  Vendor Name           object
 12  Item Number           object
 13  Item Description      object
 14  State Bottle Cost     float64
 15  State Bottle Retail   float64
 16  Bottles Sold          int64
 17  Sale (Dollars)        float64
 18  Volume Sold (Liters)  float64
dtypes: float64(4), int64(2), object(13)
memory usage: 3.8+ GB

In [28]:
iowa2['City'] = iowa2['City'].fillna('PAULLINA')
iowa2['Zip Code'] = iowa2['Zip Code'].fillna(51046)
iowa2['County'] = iowa2['County'].fillna("O'Brien")
iowa2[iowa2['County'].isna()]

Empty DataFrame
Columns: [Invoice/Item Number, Date, Store Number, Store Name, City, Zip Code, Store Location, County, Category, Category Name, Vendor Number, Vendor Name, Item Number, Item Description, State Bottle Cost, State Bottle Retail, Bottles Sold, Sale (Dollars), Volume Sold (Liters)]
Index: []

In [29]:
iowa2.isna()

,Invoice/Item Number,Date,Store Number,Store Name,City,Zip Code,Store Location,County,Category,Category Name,Vendor Number,Vendor Name,Item Number,Item Description,State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters)
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26592858,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
26592859,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
26592860,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
26592861,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
26592862,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [30]:
iowa2[iowa2.duplicated()]

Empty DataFrame
Columns: [Invoice/Item Number, Date, Store Number, Store Name, City, Zip Code, Store Location, County, Category, Category Name, Vendor Number, Vendor Name, Item Number, Item Description, State Bottle Cost, State Bottle Retail, Bottles Sold, Sale (Dollars), Volume Sold (Liters)]
Index: []

In [42]:
iowa1['County'].value_counts(dropna = False)

POLK          4906060
LINN          2208035
SCOTT         1600672
BLACK HAWK    1477835
JOHNSON       1319887
               ...
WAYNE           20790
DAVIS           19221
RINGGOLD        17641
FREMONT          6357
EL PASO             2
Name: County, Length: 101, dtype: int64

In [52]:
print(iowa1['Store Number'].value_counts()[4777])

3441

In [ ]:
county_sort = iowa1.sort_values('County')
print(county_sort)

In [ ]:
iowa1[iowa1['County'].isna()]